---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: sowmya
 spec: 
   replicas: 1
   selector:
     matchLabels:
       app: swiggy
   template:
    metadata:
     labels:
       app: swiggy
spec:
  containers:
   - name: cont-1
     image: shaikmustafa/dm
     ports:
      - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: siri
spec:
 type Loadbalancer
 selector:
   app: swiggy
 ports:
   - port: 80
     targetPort: 80
  
